// <auto-generated />
using System;
using Edri.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edri.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260215215640_AddCustomerSeedData")]
    partial class AddCustomerSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edri.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Address = "Av. Amazonas 123, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "12345678",
                            DocumentType = "DNI",
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            LastName = "Pérez García",
                            Phone = "962123456",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            Address = "Jr. Ucayali 456, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "87654321",
                            DocumentType = "DNI",
                            Email = "maria.lopez@email.com",
                            FirstName = "María",
                            LastName = "López Rodríguez",
                            Phone = "962654321",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            Address = "Av. Raymondi 789, Tingo María",
                            BusinessName = "Comercial Los Andes S.A.C.",
                            CustomerType = "Commercial",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "20123456789",
                            DocumentType = "RUC",
                            Email = "contacto@losandes.com",
                            Phone = "062562000",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            Address = "Carretera Central Km 5, Tingo María",
                            BusinessName = "Agroindustrias del Oriente S.A.",
                            CustomerType = "Industrial",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "20987654321",
                            DocumentType = "RUC",
                            Email = "info@agroindustriasoriente.com",
                            Phone = "062563000",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            Address = "Jr. Huánuco 321, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "45678912",
                            DocumentType = "DNI",
                            Email = "carlos.mendoza@email.com",
                            FirstName = "Carlos",
                            LastName = "Mendoza Silva",
                            Phone = "962789456",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Suspended",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            Address = "Av. Universitaria 555, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "CE123456",
                            DocumentType = "CE",
                            Email = "roberto.gonzalez@email.com",
                            FirstName = "Roberto",
                            LastName = "González Martínez",
                            Phone = "962111222",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000001"),
                            Code = "01",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000002"),
                            Code = "02",
                            Name = "Áncash"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000003"),
                            Code = "03",
                            Name = "Apurímac"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000004"),
                            Code = "04",
                            Name = "Arequipa"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000005"),
                            Code = "05",
                            Name = "Ayacucho"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000006"),
                            Code = "06",
                            Name = "Cajamarca"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000007"),
                            Code = "07",
                            Name = "Callao"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000008"),
                            Code = "08",
                            Name = "Cusco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000009"),
                            Code = "09",
                            Name = "Huancavelica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Code = "10",
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000011"),
                            Code = "11",
                            Name = "Ica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000012"),
                            Code = "12",
                            Name = "Junín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000013"),
                            Code = "13",
                            Name = "La Libertad"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000014"),
                            Code = "14",
                            Name = "Lambayeque"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000015"),
                            Code = "15",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000016"),
                            Code = "16",
                            Name = "Loreto"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000017"),
                            Code = "17",
                            Name = "Madre de Dios"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000018"),
                            Code = "18",
                            Name = "Moquegua"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000019"),
                            Code = "19",
                            Name = "Pasco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000020"),
                            Code = "20",
                            Name = "Piura"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000021"),
                            Code = "21",
                            Name = "Puno"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000022"),
                            Code = "22",
                            Name = "San Martín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000023"),
                            Code = "23",
                            Name = "Tacna"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000024"),
                            Code = "24",
                            Name = "Tumbes"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000025"),
                            Code = "25",
                            Name = "Ucayali"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProvinceId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.HasIndex("ProvinceId1");

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            Code = "100601",
                            Name = "Rupa-Rupa",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100602000002"),
                            Code = "100602",
                            Name = "Daniel Alomía Robles",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100603000003"),
                            Code = "100603",
                            Name = "Hermilio Valdizán",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100604000004"),
                            Code = "100604",
                            Name = "José Crespo y Castillo",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100605000005"),
                            Code = "100605",
                            Name = "Luyando",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100606000006"),
                            Code = "100606",
                            Name = "Mariano Dámaso Beraún",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100607000007"),
                            Code = "100607",
                            Name = "Pucayacu",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100608000008"),
                            Code = "100608",
                            Name = "Castillo Grande",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100609000009"),
                            Code = "100609",
                            Name = "Pueblo Nuevo",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100610000010"),
                            Code = "100610",
                            Name = "Santo Domingo de Anda",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique();

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000001"),
                            Code = "01",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000002"),
                            Code = "02",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Ambo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000003"),
                            Code = "03",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Dos de Mayo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000004"),
                            Code = "04",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huacaybamba"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000005"),
                            Code = "05",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huamalíes"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000006"),
                            Code = "06",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Leoncio Prado"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000007"),
                            Code = "07",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Marañón"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000008"),
                            Code = "08",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Pachitea"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000009"),
                            Code = "09",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Puerto Inca"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000010"),
                            Code = "10",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Lauricocha"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000011"),
                            Code = "11",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Yarowilca"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a"),
                            Name = "Admin Tenant"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastLoggedinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e3892c0-9374-49fa-a3fd-53db637a40ae"),
                            Email = "admin@email.com",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 0,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            LastName = "Pérez García",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Email = "maria.lopez@email.com",
                            FirstName = "María",
                            LastName = "López Rodríguez",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Email = "contacto@losandes.com",
                            FirstName = "Comercial",
                            LastName = "Los Andes",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Email = "info@agroindustriasoriente.com",
                            FirstName = "Agroindustrias",
                            LastName = "del Oriente",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Email = "carlos.mendoza@email.com",
                            FirstName = "Carlos",
                            LastName = "Mendoza Silva",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Email = "roberto.gonzalez@email.com",
                            FirstName = "Roberto",
                            LastName = "González Martínez",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Edri.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Edri.Domain.Entities.District", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Department", null)
                        .WithMany("Provinces")
                        .HasForeignKey("DepartmentId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Department", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
