// <auto-generated />
using System;
using Edri.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edri.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260118185503_AddDepartmentTable")]
    partial class AddDepartmentTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edri.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000001"),
                            Code = "01",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000002"),
                            Code = "02",
                            Name = "Áncash"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000003"),
                            Code = "03",
                            Name = "Apurímac"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000004"),
                            Code = "04",
                            Name = "Arequipa"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000005"),
                            Code = "05",
                            Name = "Ayacucho"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000006"),
                            Code = "06",
                            Name = "Cajamarca"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000007"),
                            Code = "07",
                            Name = "Callao"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000008"),
                            Code = "08",
                            Name = "Cusco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000009"),
                            Code = "09",
                            Name = "Huancavelica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Code = "10",
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000011"),
                            Code = "11",
                            Name = "Ica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000012"),
                            Code = "12",
                            Name = "Junín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000013"),
                            Code = "13",
                            Name = "La Libertad"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000014"),
                            Code = "14",
                            Name = "Lambayeque"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000015"),
                            Code = "15",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000016"),
                            Code = "16",
                            Name = "Loreto"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000017"),
                            Code = "17",
                            Name = "Madre de Dios"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000018"),
                            Code = "18",
                            Name = "Moquegua"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000019"),
                            Code = "19",
                            Name = "Pasco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000020"),
                            Code = "20",
                            Name = "Piura"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000021"),
                            Code = "21",
                            Name = "Puno"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000022"),
                            Code = "22",
                            Name = "San Martín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000023"),
                            Code = "23",
                            Name = "Tacna"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000024"),
                            Code = "24",
                            Name = "Tumbes"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000025"),
                            Code = "25",
                            Name = "Ucayali"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a"),
                            Name = "Admin Tenant"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastLoggedinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e3892c0-9374-49fa-a3fd-53db637a40ae"),
                            Email = "admin@email.com",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 0,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
