// <auto-generated />
using System;
using Edri.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Edri.Infrastructure.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224160121_AddReadingTable")]
    partial class AddReadingTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Edri.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("CompanyId", "Name")
                        .IsUnique();

                    b.ToTable("Branches", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Address = "Av. Amazonas 456, Tingo María",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            IsActive = true,
                            Name = "Sucursal Tingo María",
                            Phone = "062561234"
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000002"),
                            Address = "Jr. Raymondi 123, Tingo María",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            IsActive = true,
                            Name = "Sucursal Centro",
                            Phone = "062565678"
                        },
                        new
                        {
                            Id = new Guid("f1000000-0000-0000-0000-000000000003"),
                            Address = "Av. Universitaria 789, Tingo María",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000002"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            IsActive = true,
                            Name = "Agencia Leoncio Prado",
                            Phone = "062569012"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Capture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("Status");

                    b.HasIndex("Timestamp");

                    b.ToTable("Captures", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000001"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000001"),
                            ImageUrl = "/captures/2025/01/15/IOT-TM-001_080000.jpg",
                            Status = 2,
                            Timestamp = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000002"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000001"),
                            ImageUrl = "/captures/2025/01/20/IOT-TM-001_080000.jpg",
                            Status = 2,
                            Timestamp = new DateTime(2025, 1, 20, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000003"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000002"),
                            ImageUrl = "/captures/2025/01/15/IOT-TM-002_080500.jpg",
                            Status = 2,
                            Timestamp = new DateTime(2025, 1, 15, 8, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000004"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000002"),
                            ImageUrl = "/captures/2025/01/20/IOT-TM-002_080500.jpg",
                            Status = 1,
                            Timestamp = new DateTime(2025, 1, 20, 8, 5, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000005"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000003"),
                            ImageUrl = "/captures/2025/01/15/IOT-TM-003_081000.jpg",
                            Status = 2,
                            Timestamp = new DateTime(2025, 1, 15, 8, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("ca000000-0000-0000-0000-000000000006"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000003"),
                            ImageUrl = "/captures/2025/01/20/IOT-TM-003_080000.jpg",
                            Status = 3,
                            Timestamp = new DateTime(2025, 1, 20, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FiscalAddress")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character(11)")
                        .IsFixedLength();

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("TaxId")
                        .IsUnique();

                    b.ToTable("Companies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000001"),
                            BusinessName = "Electro Oriente S.A.",
                            Email = "contacto@electrooriente.com.pe",
                            FiscalAddress = "Av. Abelardo Quiñones 1245, Iquitos",
                            Phone = "065123456",
                            TaxId = "20123456789",
                            TradeName = "Electro Oriente"
                        },
                        new
                        {
                            Id = new Guid("e1000000-0000-0000-0000-000000000002"),
                            BusinessName = "Electrocentro S.A.",
                            Email = "contacto@electrocentro.com.pe",
                            FiscalAddress = "Jr. Amazonas 345, Huancayo",
                            Phone = "064234567",
                            TaxId = "20987654321",
                            TradeName = "Electrocentro"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("BusinessName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CustomerType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DocumentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Customers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000001"),
                            Address = "Av. Amazonas 123, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "12345678",
                            DocumentType = "DNI",
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            LastName = "Pérez García",
                            Phone = "962123456",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000002"),
                            Address = "Jr. Ucayali 456, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "87654321",
                            DocumentType = "DNI",
                            Email = "maria.lopez@email.com",
                            FirstName = "María",
                            LastName = "López Rodríguez",
                            Phone = "962654321",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000003"),
                            Address = "Av. Raymondi 789, Tingo María",
                            BusinessName = "Comercial Los Andes S.A.C.",
                            CustomerType = "Commercial",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "20123456789",
                            DocumentType = "RUC",
                            Email = "contacto@losandes.com",
                            Phone = "062562000",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000004"),
                            Address = "Carretera Central Km 5, Tingo María",
                            BusinessName = "Agroindustrias del Oriente S.A.",
                            CustomerType = "Industrial",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "20987654321",
                            DocumentType = "RUC",
                            Email = "info@agroindustriasoriente.com",
                            Phone = "062563000",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000005"),
                            Address = "Jr. Huánuco 321, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "45678912",
                            DocumentType = "DNI",
                            Email = "carlos.mendoza@email.com",
                            FirstName = "Carlos",
                            LastName = "Mendoza Silva",
                            Phone = "962789456",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Suspended",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = new Guid("b1000000-0000-0000-0000-000000000006"),
                            Address = "Av. Universitaria 555, Tingo María",
                            CustomerType = "Residential",
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            DocumentNumber = "CE123456",
                            DocumentType = "CE",
                            Email = "roberto.gonzalez@email.com",
                            FirstName = "Roberto",
                            LastName = "González Martínez",
                            Phone = "962111222",
                            RegistrationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Active",
                            UserId = new Guid("a1000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000001"),
                            Code = "01",
                            Name = "Amazonas"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000002"),
                            Code = "02",
                            Name = "Áncash"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000003"),
                            Code = "03",
                            Name = "Apurímac"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000004"),
                            Code = "04",
                            Name = "Arequipa"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000005"),
                            Code = "05",
                            Name = "Ayacucho"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000006"),
                            Code = "06",
                            Name = "Cajamarca"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000007"),
                            Code = "07",
                            Name = "Callao"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000008"),
                            Code = "08",
                            Name = "Cusco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000009"),
                            Code = "09",
                            Name = "Huancavelica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Code = "10",
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000011"),
                            Code = "11",
                            Name = "Ica"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000012"),
                            Code = "12",
                            Name = "Junín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000013"),
                            Code = "13",
                            Name = "La Libertad"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000014"),
                            Code = "14",
                            Name = "Lambayeque"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000015"),
                            Code = "15",
                            Name = "Lima"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000016"),
                            Code = "16",
                            Name = "Loreto"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000017"),
                            Code = "17",
                            Name = "Madre de Dios"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000018"),
                            Code = "18",
                            Name = "Moquegua"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000019"),
                            Code = "19",
                            Name = "Pasco"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000020"),
                            Code = "20",
                            Name = "Piura"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000021"),
                            Code = "21",
                            Name = "Puno"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000022"),
                            Code = "22",
                            Name = "San Martín"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000023"),
                            Code = "23",
                            Name = "Tacna"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000024"),
                            Code = "24",
                            Name = "Tumbes"
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000025"),
                            Code = "25",
                            Name = "Ucayali"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(17)
                        .HasColumnType("character varying(17)");

                    b.Property<Guid>("MeterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Model")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("MeterId");

                    b.HasIndex("Status");

                    b.ToTable("Devices", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("de000000-0000-0000-0000-000000000001"),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Code = "IOT-TM-001",
                            FirmwareVersion = "1.0.0",
                            InstallationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastConnection = new DateTime(2025, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            MacAddress = "AA:BB:CC:DD:EE:01",
                            MeterId = new Guid("c2000000-0000-0000-0000-000000000001"),
                            Model = "ESP32-CAM",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("de000000-0000-0000-0000-000000000002"),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Code = "IOT-TM-002",
                            FirmwareVersion = "1.0.0",
                            InstallationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastConnection = new DateTime(2025, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            MacAddress = "AA:BB:CC:DD:EE:02",
                            MeterId = new Guid("c2000000-0000-0000-0000-000000000002"),
                            Model = "ESP32-CAM",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("de000000-0000-0000-0000-000000000003"),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Code = "IOT-TM-003",
                            FirmwareVersion = "2.1.0",
                            InstallationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastConnection = new DateTime(2025, 1, 20, 10, 30, 0, 0, DateTimeKind.Utc),
                            MacAddress = "AA:BB:CC:DD:EE:03",
                            MeterId = new Guid("c2000000-0000-0000-0000-000000000003"),
                            Model = "Raspberry Pi 4",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("de000000-0000-0000-0000-000000000004"),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            Code = "IOT-TM-004",
                            FirmwareVersion = "2.1.0",
                            InstallationDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MacAddress = "AA:BB:CC:DD:EE:04",
                            MeterId = new Guid("c2000000-0000-0000-0000-000000000004"),
                            Model = "Raspberry Pi 4",
                            Status = 3
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.District", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character(6)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("ProvinceId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ProvinceId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ProvinceId");

                    b.HasIndex("ProvinceId1");

                    b.ToTable("Districts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            Code = "100601",
                            Name = "Rupa-Rupa",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100602000002"),
                            Code = "100602",
                            Name = "Daniel Alomía Robles",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100603000003"),
                            Code = "100603",
                            Name = "Hermilio Valdizán",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100604000004"),
                            Code = "100604",
                            Name = "José Crespo y Castillo",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100605000005"),
                            Code = "100605",
                            Name = "Luyando",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100606000006"),
                            Code = "100606",
                            Name = "Mariano Dámaso Beraún",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100607000007"),
                            Code = "100607",
                            Name = "Pucayacu",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100608000008"),
                            Code = "100608",
                            Name = "Castillo Grande",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100609000009"),
                            Code = "100609",
                            Name = "Pueblo Nuevo",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        },
                        new
                        {
                            Id = new Guid("d7f8f0a1-0000-0000-0000-100610000010"),
                            Code = "100610",
                            Name = "Santo Domingo de Anda",
                            ProvinceId = new Guid("a1b2c3d4-0000-0000-0000-100000000006")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Meter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AmperageCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("Brand")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastCalibrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplyId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MeterNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SupplyId");

                    b.ToTable("Meters", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000001"),
                            AmperageCapacity = 30,
                            Brand = "ELSTER",
                            InstallationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastCalibrationDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MeterNumber = "MED-2025-000001",
                            Model = "A1100",
                            Status = 1,
                            SupplyId = new Guid("d1000000-0000-0000-0000-000000000001"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000002"),
                            AmperageCapacity = 40,
                            Brand = "LANDIS+GYR",
                            InstallationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastCalibrationDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MeterNumber = "MED-2025-000002",
                            Model = "E350",
                            Status = 1,
                            SupplyId = new Guid("d1000000-0000-0000-0000-000000000002"),
                            Type = 2
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000003"),
                            AmperageCapacity = 60,
                            Brand = "ITRON",
                            InstallationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastCalibrationDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MeterNumber = "MED-2025-000003",
                            Model = "OpenWay Riva",
                            Status = 1,
                            SupplyId = new Guid("d1000000-0000-0000-0000-000000000003"),
                            Type = 3
                        },
                        new
                        {
                            Id = new Guid("c2000000-0000-0000-0000-000000000004"),
                            AmperageCapacity = 100,
                            Brand = "SCHNEIDER",
                            InstallationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LastCalibrationDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            MeterNumber = "MED-2025-000004",
                            Model = "ION8650",
                            Status = 1,
                            SupplyId = new Guid("d1000000-0000-0000-0000-000000000004"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character(2)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId1");

                    b.HasIndex("DepartmentId", "Code")
                        .IsUnique();

                    b.ToTable("Provinces", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000001"),
                            Code = "01",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huánuco"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000002"),
                            Code = "02",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Ambo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000003"),
                            Code = "03",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Dos de Mayo"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000004"),
                            Code = "04",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huacaybamba"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000005"),
                            Code = "05",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Huamalíes"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000006"),
                            Code = "06",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Leoncio Prado"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000007"),
                            Code = "07",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Marañón"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000008"),
                            Code = "08",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Pachitea"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000009"),
                            Code = "09",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Puerto Inca"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000010"),
                            Code = "10",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Lauricocha"
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-0000-0000-0000-100000000011"),
                            Code = "11",
                            DepartmentId = new Guid("d7f8f0a1-1b1a-4b1a-8b1a-000000000010"),
                            Name = "Yarowilca"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Reading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CaptureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("MeterNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observations")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("OcrConfidence")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("ReadingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValueKwh")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("CaptureId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("MeterNumber");

                    b.HasIndex("ReadingDate");

                    b.HasIndex("MeterNumber", "ReadingDate");

                    b.ToTable("Readings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000001"),
                            CaptureId = new Guid("ca000000-0000-0000-0000-000000000001"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000001"),
                            MeterNumber = "MED-2025-000001",
                            OcrConfidence = 98.5m,
                            ReadingDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 1,
                            ValueKwh = 1250.50m
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000002"),
                            CaptureId = new Guid("ca000000-0000-0000-0000-000000000002"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000001"),
                            MeterNumber = "MED-2025-000001",
                            OcrConfidence = 99.1m,
                            ReadingDate = new DateTime(2025, 1, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 1,
                            ValueKwh = 1320.75m
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000003"),
                            CaptureId = new Guid("ca000000-0000-0000-0000-000000000003"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000002"),
                            MeterNumber = "MED-2025-000002",
                            OcrConfidence = 97.8m,
                            ReadingDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 1,
                            ValueKwh = 980.25m
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000004"),
                            CaptureId = new Guid("ca000000-0000-0000-0000-000000000005"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000003"),
                            MeterNumber = "MED-2025-000003",
                            OcrConfidence = 99.5m,
                            ReadingDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 1,
                            ValueKwh = 5420.00m
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000005"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000004"),
                            MeterNumber = "MED-2025-000004",
                            Observations = "Lectura manual - dispositivo en mantenimiento",
                            ReadingDate = new DateTime(2025, 1, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 2,
                            ValueKwh = 15800.00m
                        },
                        new
                        {
                            Id = new Guid("ae000000-0000-0000-0000-000000000006"),
                            DeviceId = new Guid("de000000-0000-0000-0000-000000000002"),
                            MeterNumber = "MED-2025-000002",
                            Observations = "Lectura estimada basada en consumo promedio histórico",
                            ReadingDate = new DateTime(2025, 1, 20, 8, 0, 0, 0, DateTimeKind.Utc),
                            Source = 3,
                            ValueKwh = 1045.00m
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Supply", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DistrictId")
                        .HasColumnType("uuid");

                    b.Property<string>("InstallationAddress")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Reference")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SupplyNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("TariffId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("TerminationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("Status");

                    b.HasIndex("SupplyNumber")
                        .IsUnique();

                    b.HasIndex("TariffId");

                    b.ToTable("Supplies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000001"),
                            ActivationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("b1000000-0000-0000-0000-000000000001"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            InstallationAddress = "Av. Amazonas 123, Tingo María",
                            Latitude = -9.2950m,
                            Longitude = -76.0000m,
                            Reference = "Frente al parque principal",
                            Status = "Active",
                            SupplyNumber = "SUM-2025-000001",
                            TariffId = new Guid("aa000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000002"),
                            ActivationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("b1000000-0000-0000-0000-000000000002"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            InstallationAddress = "Jr. Ucayali 456, Tingo María",
                            Latitude = -9.2960m,
                            Longitude = -76.0010m,
                            Reference = "Cerca del mercado",
                            Status = "Active",
                            SupplyNumber = "SUM-2025-000002",
                            TariffId = new Guid("aa000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000003"),
                            ActivationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("b1000000-0000-0000-0000-000000000003"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            InstallationAddress = "Av. Raymondi 789, Tingo María",
                            Latitude = -9.2940m,
                            Longitude = -75.9990m,
                            Reference = "Local comercial esquina",
                            Status = "Active",
                            SupplyNumber = "SUM-2025-000003",
                            TariffId = new Guid("aa000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = new Guid("d1000000-0000-0000-0000-000000000004"),
                            ActivationDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            BranchId = new Guid("f1000000-0000-0000-0000-000000000001"),
                            CustomerId = new Guid("b1000000-0000-0000-0000-000000000004"),
                            DistrictId = new Guid("d7f8f0a1-0000-0000-0000-100601000001"),
                            InstallationAddress = "Carretera Central Km 5, Tingo María",
                            Latitude = -9.2800m,
                            Longitude = -75.9850m,
                            Reference = "Zona industrial",
                            Status = "Active",
                            SupplyNumber = "SUM-2025-000004",
                            TariffId = new Guid("aa000000-0000-0000-0000-000000000005")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tariff", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FixedCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("PricePerKwh")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Tariffs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000001"),
                            Code = "BT5B",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Description = "Tarifa para consumo residencial hasta 100 kWh",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedCharge = 3.26m,
                            IsActive = true,
                            Name = "Tarifa Residencial BT5B",
                            PricePerKwh = 0.7520m
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000002"),
                            Code = "BT5A",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Description = "Tarifa para consumo residencial mayor a 100 kWh",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedCharge = 3.26m,
                            IsActive = true,
                            Name = "Tarifa Residencial BT5A",
                            PricePerKwh = 0.8150m
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000003"),
                            Code = "BT4",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000001"),
                            Description = "Tarifa para uso comercial",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedCharge = 5.50m,
                            IsActive = true,
                            Name = "Tarifa Comercial BT4",
                            PricePerKwh = 0.6890m
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000004"),
                            Code = "BT5B",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000002"),
                            Description = "Tarifa para consumo residencial hasta 100 kWh",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedCharge = 3.10m,
                            IsActive = true,
                            Name = "Tarifa Residencial BT5B",
                            PricePerKwh = 0.7350m
                        },
                        new
                        {
                            Id = new Guid("aa000000-0000-0000-0000-000000000005"),
                            Code = "MT3",
                            CompanyId = new Guid("e1000000-0000-0000-0000-000000000002"),
                            Description = "Tarifa para uso industrial en media tensión",
                            EffectiveFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FixedCharge = 25.00m,
                            IsActive = true,
                            Name = "Tarifa Industrial MT3",
                            PricePerKwh = 0.5200m
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a"),
                            Name = "Admin Tenant"
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastLoggedinDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e3892c0-9374-49fa-a3fd-53db637a40ae"),
                            Email = "admin@email.com",
                            FirstName = "Admin",
                            LastName = "User",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 0,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000001"),
                            Email = "juan.perez@email.com",
                            FirstName = "Juan",
                            LastName = "Pérez García",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000002"),
                            Email = "maria.lopez@email.com",
                            FirstName = "María",
                            LastName = "López Rodríguez",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000003"),
                            Email = "contacto@losandes.com",
                            FirstName = "Comercial",
                            LastName = "Los Andes",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000004"),
                            Email = "info@agroindustriasoriente.com",
                            FirstName = "Agroindustrias",
                            LastName = "del Oriente",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000005"),
                            Email = "carlos.mendoza@email.com",
                            FirstName = "Carlos",
                            LastName = "Mendoza Silva",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        },
                        new
                        {
                            Id = new Guid("a1000000-0000-0000-0000-000000000006"),
                            Email = "roberto.gonzalez@email.com",
                            FirstName = "Roberto",
                            LastName = "González Martínez",
                            Password = "$2a$12$Blal/uiFIJdYsCLTMUik/egLbfg3XhbnxBC6Sb5IKz2ZYhiU/MzL2",
                            Role = 2,
                            Status = 0,
                            TenantId = new Guid("b542bf25-134c-47a2-a0df-84ed14d03c4a")
                        });
                });

            modelBuilder.Entity("Edri.Domain.Entities.Branch", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Capture", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Customer", b =>
                {
                    b.HasOne("Edri.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Device", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Meter", "Meter")
                        .WithMany()
                        .HasForeignKey("MeterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Meter");
                });

            modelBuilder.Entity("Edri.Domain.Entities.District", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Province", null)
                        .WithMany("Districts")
                        .HasForeignKey("ProvinceId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Meter", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Supply", "Supply")
                        .WithMany()
                        .HasForeignKey("SupplyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supply");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Department", null)
                        .WithMany("Provinces")
                        .HasForeignKey("DepartmentId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Reading", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Capture", "Capture")
                        .WithMany()
                        .HasForeignKey("CaptureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Edri.Domain.Entities.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Capture");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Supply", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Edri.Domain.Entities.Tariff", "Tariff")
                        .WithMany()
                        .HasForeignKey("TariffId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("Tariff");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tariff", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Edri.Domain.Entities.User", b =>
                {
                    b.HasOne("Edri.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Department", b =>
                {
                    b.Navigation("Provinces");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Province", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Edri.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
